from django.db import models

class Catergory(models.Model):
    name = ...


class Products(models.Model):
    productName = ...
    productPrice = ...
    productCategory = ...
    productDesc = ...
    productImage = ...
    quantityAvailable = ...

class Cart(models.Model):
    customer = ...
    product = ...
    quantity = ...    


