# Generated by Django 4.1.7 on 2023-03-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=150)),
                ('productPrice', models.IntegerField()),
                ('productDesc', models.TextField()),
                ('productImage', models.ImageField(upload_to='media')),
                ('quantityAvailable', models.IntegerField()),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.catergory')),
            ],
        ),
    ]
